harp/harp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('machines.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

harp/machines/urls.py
from django.urls import path

from . import views
from .views import cad_file_queue

app_name = 'machines'


urlpatterns = [
    path('', views.DashboardView.as_view(), name='dashboard'),
    path('queue/', views.QueueView.as_view(), name='queue'),
    path('queue/<int:pk>/delete', views.queue_delete, name='queue_delete'),
    path('queue/<int:pk>/up', views.queue_up, name='queue_up'),
    path('queue/<int:pk>/down', views.queue_down, name='queue_down'),
    path('queue/<int:pk>/repeat', views.queue_repeat, name='queue_repeat'),
    path('cad', views.CADFileViewAll.as_view(), name='cad'),
    path('cad/add', views.CADFileCreate.as_view(), name='cad_add'),
    path('cad/<int:pk>/', views.CADFileView.as_view(), name='cad_view'),
    path('cad/<int:pk>/edit', views.CADFileEditView.as_view(), name='cad_edit'),
    path('cad/<int:pk>/delete', views.cad_delete, name='cad_delete'),
    path('cad/<int:pk>/queue', views.cad_file_queue, name='cad_queue'),
    path('machines/', views.PrintersView.as_view(), name='machines'),
    path('machines/add', views.PrinterCreate.as_view(), name='machine_add'),
    path('machines/<int:pk>/delete', views.machine_delete, name='machine_delete'),
    path('machines/<int:pk>/clear_bed', views.mark_printer_cleared, name='clear_bed'),
    path('machines/<int:pk>/online', views.printer_offline_check, name='machine_online_checkbox'),
    path('external/pushover/add', views.PushoverCreate.as_view(), name='pushover_create')
]

harp/machines/models.py
import hashlib
import json
import os
import subprocess
import uuid

from io import IOBase
from json.decoder import JSONDecodeError
from datetime import timedelta
from shutil import copyfile

import requests
from django.db import models

from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils import timezone
from django.utils.timezone import now
from tagulous.models import TagField

from .errors import *

PRINTER_STATUS = '/api/printer'
FILES_UPLOAD = '/api/files/local'
JOB_STATUS = '/api/job'


class FileType(models.TextChoices):
    GCODE = 'Gcode'
    STL = 'STL'


class CADFile(models.Model):
    name = models.CharField(max_length=200)
    file = models.FileField(upload_to='cad/')
    file_type = models.CharField(max_length=100, choices=FileType.choices, default=FileType.STL)
    machine_tags = TagField()
    tags = TagField()


class Printer(models.Model):
    class PrinterStatus(models.TextChoices):
        PRINT_DONE = 'Print Done'
        READY = 'Ready'
        PRINTING = 'Printing'
        CLEARED = 'Clear Bed'
        OFFLINE = 'Offline'

    name = models.CharField(max_length=200)
    octoprint = models.URLField()
    api_key = models.CharField(max_length=64)
    status = models.CharField(max_length=100, choices=PrinterStatus.choices, default=PrinterStatus.PRINT_DONE)
    last_updated = models.DateTimeField('last checked', default=now)
    online = models.BooleanField(default=True)
    config = models.FileField(upload_to='printer_config/')
    eta = models.DateTimeField('eta', default=now)
    percent_done = models.FloatField(default=0)
    tags = TagField()

    def get_status(self):
        headers = {'X-Api-Key': self.api_key}
        r = requests.get(self.octoprint + PRINTER_STATUS, headers=headers)
        try:
            return json.loads(r.content)
        except JSONDecodeError:
            return 'offline'

    def set_status(self):
        x = self.get_status()

        if x == 'offline':
            self.last_updated = timezone.now()
            self.status = Printer.PrinterStatus.OFFLINE
            self.save()
            return

        ready = x['state']['flags']['ready']
        printing = x['state']['flags']['printing']
        current_status = self.status

        if printing:
            self.status = Printer.PrinterStatus.PRINTING
            self.set_print_eta()
        elif ready:
            if self.status == Printer.PrinterStatus.PRINTING:
                self.status = Printer.PrinterStatus.PRINT_DONE
        else:
            self.status = Printer.PrinterStatus.PRINT_DONE

        self.last_updated = timezone.now()

        if self.status == Printer.PrinterStatus.PRINT_DONE and current_status != self.status:
            pushovers = PushoverCall.objects.filter(printer=self.pk)

            for pushover in pushovers:
                pushover.send_message()

        self.save()

    def mark_printer_cleared(self):
        x = self.get_status()

        if x == 'offline' or x['state']['flags']['ready']:
            self.status = Printer.PrinterStatus.READY
            self.save()

    def upload_new_gcode_file(self, gcode_pk):
        gcode = Gcode.objects.get(pk=gcode_pk)

        headers = {'X-Api-Key': self.api_key}
        fle = {'file': open(gcode.file.path, 'rb'), 'filename': os.path.basename(gcode.file.name)}

        r = requests.post(self.octoprint + FILES_UPLOAD, headers=headers, files=fle)

        if r.status_code == 400:
            raise PrinterGcodeNoFile()
        elif r.status_code == 404:
            raise PrinterGcodeWrongUploadLocation()
        elif r.status_code == 409:
            raise PrinterGcodeFileExists()
        elif r.status_code == 415:
            raise PrinterGcodeWrongFiletype()
        elif r.status_code == 500:
            raise Printer500Error()

    def check_file_exists(self, gcode_pk):
        gcode = Gcode.objects.get(pk=gcode_pk)

        headers = {'X-Api-Key': self.api_key}
        r = requests.get(self.octoprint + FILES_UPLOAD + '/' + os.path.basename(gcode.file.name), headers=headers)

        if r.status_code == 404:
            return False

        remote_hash = json.loads(r.text)['hash']

        local_hash: str = hashlib.sha1(open(gcode.file.name, 'rb').read()).hexdigest()

        return remote_hash == local_hash

    def start_print(self, gcode_pk):
        gcode = Gcode.objects.get(pk=gcode_pk)

        if self.status == Printer.PrinterStatus.READY:
            if not self.check_file_exists(gcode_pk):
                self.upload_new_gcode_file(gcode_pk)

            headers = {'X-Api-Key': self.api_key}
            data = {'command': 'select', 'print': 'true'}
            r = requests.post(self.octoprint + FILES_UPLOAD + '/' + os.path.basename(gcode.file.name),
                              headers=headers, json=data)

            if r.status_code == 409:
                raise MachineUnavailable()

    def cancel_current_job(self):
        headers = {'X-Api-Key': self.api_key}
        data = {'command': 'cancel'}
        requests.post(self.octoprint + JOB_STATUS, headers=headers, json=data)

    def set_print_eta(self):
        headers = {'X-Api-Key': self.api_key}
        r = requests.get(self.octoprint + JOB_STATUS, headers=headers)
        r = json.loads(r.content)
        seconds = r['progress']['printTimeLeft']
        percent = r['progress']['completion']

        try:
            self.eta = timezone.now() + timedelta(seconds=seconds)
        except TypeError:
            # Essentially the eta has not returned a number.
            self.eta = timezone.now()

        # Percent will be None if there isn't a print going on.
        if percent is not None:
            self.percent_done = percent
        else:
            self.percent_done = 0

        self.save()

    def create_gcode(self, file: CADFile) -> IOBase:
        """
        Returns a filehandle of a generated gcode file.
        """
        if file.file_type == FileType.STL.name:
            try:
                stl = file.file.path
                # generate unique name for the gcode
                name = 'gcode/' + str(uuid.uuid1()) + '.gcode'
                subprocess.check_output(['./PrusaSlicer.AppImage',
                                         '--load', self.config.path,
                                         '--export-gcode',
                                         '--output', name,
                                         stl])
                return open(name, 'r+')
            except subprocess.CalledProcessError as e:
                print(e.output)
        elif file.file_type == FileType.GCODE:
            try:
                # We cut off the first 4 characters of file.file.name
                # because it includes the cad/ directory in the name.
                return open(copyfile(file.file.path, 'gcode/' + file.file.name[4:]), 'r+')
            except Exception as e:
                print(e.output)

    def __str__(self):
        return self.name


class Gcode(models.Model):
    """
    This represents a base level file that goes directly to a machine.
    :file: Saved gcode file.
    :machine: Specific machine this gcode is tied to.
    :parent_cad: The originating CAD File that was used to generate this gcode file.
    """
    file = models.FileField(upload_to='gcode/')
    machine = models.ForeignKey(Printer, on_delete=models.CASCADE, null=True)
    parent_cad = models.ForeignKey(CADFile, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.name


class QueueItem(models.Model):
    position = models.IntegerField()
    cad_file = models.ForeignKey(CADFile, on_delete=models.CASCADE)
    currently_printing = models.BooleanField(default=False)
    amount_to_print = models.IntegerField(default=1)

class PushoverCall(models.Model):
    printer = models.ForeignKey(Printer, on_delete=models.CASCADE)
    token = models.CharField(max_length=64)
    user = models.CharField(max_length=64)
    body = models.CharField(max_length=250)
    
    def send_message(self):
        data = {'token': self.token,
                'user': self.user,
                'message': self.body,
                'title': self.printer.name + ' | HARP'}

        res = requests.post('https://api.pushover.net/1/messages.json', data=data)
        print('----')
        print(res.json())

    @classmethod
    def post_create(cls, sender, instance, created, *args, **kwargs):
        if not created:
            return
        instance.send_message()

class Trigger(models.Model):
    printer = models.ForeignKey(Printer, on_delete=models.CASCADE)


@receiver(models.signals.post_delete, sender=Gcode)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Deletes file from filesystem, when corresponding Gcode object is deleted.
    """
    if instance.file:
        if os.path.isfile(instance.file.path):
            os.remove(instance.file.path)

post_save.connect(PushoverCall.post_create, sender=PushoverCall)

harp/machines/forms.py
from django import forms
from django.forms import ModelForm, Form, FileField, FileInput

from .models import Gcode, Printer


class AddPrinterForm(ModelForm):
    class Meta:
        model = Printer
        fields = ['name', 'octoprint', 'api_key', 'tags']

harp/machines/views.py
import json

from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect
from django.urls import reverse
from django.views import generic
from django.views.generic import CreateView, UpdateView, DetailView

from .models import Printer, Gcode, QueueItem, CADFile, PushoverCall
from .forms import AddPrinterForm

def get_next_queue_position():
    last_queue_item = QueueItem.objects.order_by('position').last()
    queue_position = 1

    if last_queue_item is not None:
        queue_position = last_queue_item.position + 1

    return queue_position

class DashboardView(generic.ListView):
    model = Printer
    template_name = 'machines/dashboard.html'
    context_object_name = 'printers'


class QueueView(generic.ListView):
    template_name = 'machines/queue.html'
    context_object_name = 'queue'

    def get_queryset(self):
        queue_compact()
        return QueueItem.objects.order_by('position')


def queue_delete(request, pk):
    q = QueueItem.objects.get(pk=pk)
    q.delete()

    return redirect('machines:queue')


def queue_repeat(request, pk):
    if request.method == 'POST':
        data = json.loads(request.body.decode('utf-8'))
        qi = QueueItem.objects.get(pk=pk)
        qi.amount_to_print = int(data['count'])
        qi.save()

    return JsonResponse({'hi':'hi'})


class PrintersView(generic.ListView):
    model = Printer
    template_name = 'machines/printers.html'
    context_object_name = 'printers'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['add_printer_form'] = AddPrinterForm()
        return context


class PrinterCreate(CreateView):
    model = Printer
    fields = ['name', 'octoprint', 'api_key', 'config', 'tags']

    def get_success_url(self):
        return reverse('machines:machines')


class PrinterUpdate(UpdateView):
    model = Printer
    fields = ['__all__']

def machine_delete(request, pk):
    machine = Printer.objects.get(pk=pk)
    machine.delete()

    return redirect('machines:machines')


class CADFileViewAll(generic.ListView):
    model = CADFile
    fields = ['__all__']
    context_object_name = 'cad_files'
    queryset = CADFile.objects.all().order_by('tags')


class CADFileCreate(CreateView):
    model = CADFile
    fields = ['name', 'file', 'file_type', 'machine_tags', 'tags']

    # This is called if the user clicks the Add and Queue button.
    def post(self, request):
        x = super(CADFileCreate, self).post(request)
        if request.POST.get('add_and_queue'):
            queue_position = get_next_queue_position()
            cad_file = CADFile.objects.get(pk=self.object.id)
            q = QueueItem(position=queue_position, cad_file=cad_file)
            q.save()

        return x

    def get_success_url(self):
        return reverse('machines:cad')


class CADFileEditView(UpdateView):
    model = CADFile
    fields = ['name', 'machine_tags', 'tags']
    template_name_suffix = '_edit'

    def get_success_url(self):
        return reverse('machines:cad')


class CADFileView(DetailView):
    model = CADFile
    fields = ['__all__']


class PushoverCreate(CreateView):
    model = PushoverCall
    fields = ['printer', 'token', 'user', 'body']

    def get_success_url(self):
        return reverse('machines:machines')



def cad_file_queue(request, pk):
    cad_file = CADFile.objects.get(pk=pk)
    
    queue_position = get_next_queue_position()

    q = QueueItem(position=queue_position, cad_file=cad_file)
    q.save()

    return redirect('machines:cad')


def cad_delete(request, pk):
    cad_file = CADFile.objects.get(pk=pk)
    cad_file.delete()

    return redirect('machines:cad')


def printer_add(request):
    form = AddPrinterForm(request.POST)

    try:
        form.save()
    except ValueError:
        print('bad')

    return redirect('machines:machines')


def printer_offline_check(request, pk):
    if request.method == "POST":
        printer = Printer.objects.get(pk=pk)
        if 'online' in request.POST:
            printer.online = True
        else:
            printer.online = False

        printer.save()
        return redirect('machines:machines')
    else:
        return HttpResponse(status=400)


def mark_printer_cleared(request, pk):
    Printer.objects.get(pk=pk).mark_printer_cleared()
    return redirect('machines:dashboard')


def queue_up(request, pk):
    qi: QueueItem = QueueItem.objects.get(pk=pk)
    qip: QueueItem = QueueItem.objects.get(position=(qi.position-1))

    if qip is None:
        qi.position = qi.position-1
        qi.save()
    else:
        qi_pos = qi.position
        qi.position = qi_pos-1
        qi.save()
        qip.position = qi_pos
        qip.save()

    return redirect('machines:queue')


def queue_down(request, pk):
    qi: QueueItem = QueueItem.objects.get(pk=pk)
    qip: QueueItem = QueueItem.objects.get(position=(qi.position+1))

    if qip is not None:
        qi_pos = qi.position
        qi.position = qi_pos + 1
        qi.save()
        qip.position = qi_pos
        qip.save()

    return redirect('machines:queue')


def queue_compact():
    open_spot = 1
    for qi in QueueItem.objects.all().order_by('position'):
        if qi.position > open_spot:
            qi.position = open_spot
            open_spot = open_spot + 1
            qi.save()
        else:
            open_spot = open_spot + 1


def clear_gcode():
    gc_none = Gcode.objects.all().exclude(parent_cad=None)

    for x in gc_none:
        x.delete()


def external_queue(request):
    if request.method == "POST":
        pass

harp/machines/templates/machines/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'machines/style.css' %}">
    {% block head %} {% endblock %}
</head>
<body>
<div class="nav">
    <ul>
        <li><a href="{% url 'machines:dashboard' %}">Dashboard</a></li>
        <li><a href="{% url 'machines:queue' %}">Queue</a></li>
        <li><a href="{% url 'machines:machines' %}">Printers</a></li>
        <li><a href="{% url 'machines:cad' %}">CAD Files</a></li>
    </ul>
</div>
    {% block content %}
    {% endblock %}

<script>
function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = cookies[i].trim();
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }

    return cookieValue;
}
</script>
{% block script %}
{% endblock %}
</body>
</html>

harp/machines/templates/machines/cadfile_edit.html
{% extends 'machines/base.html' %}
{% load static %}

{% block content %}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Edit">
</form>
{% endblock %}

harp/machines/templates/machines/cadfile_form.html
{% extends 'machines/base.html' %}
{% load static %}

{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" name='add' value="Add">
    <input type="submit" name='add_and_queue' value="Add and Queue">
</form>
{% endblock %}

harp/machines/templates/machines/cadfile_list.html
{% extends 'machines/base.html' %}
{% load static %}

{% block head%}
<script src="{% static 'machines/alertify.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'machines/alertify.min.css' %}" />
<link rel="stylesheet" href="{% static 'machines/themes/default.min.css' %}" />
{% endblock head %}

{% block content %}
<a href="{% url 'machines:cad_add' %}">Add CAD File</a>
<input type="text" id="searchInput" onkeyup="search()" placeholder="Search..">
<table>
    <thead>
    <tr>
        <th>Name</th>
        <th>Tags</th>
        <th>Add to Queue</th>
        <th>Edit</th>
        <th>Delete</th>
        <th>Will Run On</th>
    </tr>
    </thead>
    <tbody>
        {% for file in cad_files %}
        <tr>
            <td>{{ file.name }}</td>
            <td>
                {% for tag in file.tags.all %}
                    <span class="tag-pill">{{ tag.name }}</span>
                {% endfor %}
            </td>
            <td>
                <button class="add_queue" data-pk={{ file.pk }} data-name="{{ file.name }}">Add to Queue.</button>
            </td>
            <td>
                <a href="{% url 'machines:cad_edit' file.id %}">Edit</a>
            </td>
            <td>
                <button class='delete_cadfile' data-pk={{ file.pk }} data-name="{{ file.name }}">Delete</button>
            </td>
            <td>
                {% for tag in file.machine_tags.all %}
                    <span class="tag-pill">{{ tag.name }}</span>
                {% endfor %}
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

{% block script %}
<script>
function search() {
    // Declare variables
    var input, filter, table, tr, td, i, j, tds, ths, matched;
    input = document.getElementById("searchInput");
    filter = input.value.toUpperCase();
    tr = document.getElementsByTagName("tr");

    // Loop through all table rows, and hide
    // those who don't match the search query
    for (i = 0; i < tr.length; i++) {
        tds = tr[i].getElementsByTagName("td");
        ths = tr[i].getElementsByTagName("th");
        matched = false;

        // leave the row header
        if (ths.length > 0) {
            matched = true;
        }
        else {
            for (j = 0; j < tds.length; j++) {
                td = tds[j];
                if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                    matched = true;
                    break;
                }

            }
        }
        if (matched == true) {
            tr[i].style.display = "";
        }
        else {
            tr[i].style.display = "none";
        }
    }
}

const repeatElement = document.querySelectorAll('.add_queue')

repeatElement.forEach(function(item) {
    item.addEventListener('click', (event) => {
        const item_pk = event.target.getAttribute('data-pk');
        const item_name = event.target.getAttribute('data-name');
        console.log(event.target.value);
        data = JSON.stringify({count: event.target.value});
        let csrftoken = getCookie('csrftoken');
        let response = fetch('/cad/' + item_pk + '/queue', {
            method: "POST",
            body: data,
            headers: { 'Accept': 'application/json, text/plain, */*',
                        'Content-Type': 'application/json',
                        "X-CSRFToken": csrftoken },
        });
        alertify.success(item_name + ' added to queue.');
    });
});

const deleteElement = document.querySelectorAll('.delete_cadfile');

deleteElement.forEach(function(item) {
    item.addEventListener('click', (event) => {
        const item_pk = event.target.getAttribute('data-pk');
        const item_name = event.target.getAttribute('data-name');

        let csrftoken = getCookie('csrftoken')

        if(confirm("Delete " + item_name + "?")) {
            let response = fetch('/cad/' + item_pk + '/delete', {
                method: "POST",
                headers: {
                    'Accept': 'application/json, text/plain, */*',
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrftoken 
                },
            });
            location.reload();
        }
    });
});
</script>
{% endblock %}

harp/machines/templates/machines/dashboard.html
{% extends 'machines/base.html' %}
{% load static %}

{% block head %}
<meta http-equiv="refresh" content="60">
{% endblock %}

{% block content %}
<h1>Dashboard</h1>
<h3>Filter By</h3>
<div class="filter-bar">
    <div>
        <input type="checkbox" id="ready" name="ready" checked>
        <label for="ready">Ready</label>
    </div>
    <div>
        <input type="checkbox" id="check" name="check" checked>
        <label for="ready">Check</label>
    </div>
    <div>
        <input type="checkbox" id="printing" name="printing" checked>
        <label for="ready">Printing</label>
    </div>
    <div>
        <input type="checkbox" id="unknown" name="unknown" checked>
        <label for="ready">Unknown</label>
    </div>
</div>
<div class="dashboard-items">
    {% for printer in printers %}
        <div class="card">
            <h4>{{ printer.name }}</h4>
            <p class="last-checked">Last checked: {{ printer.last_updated|timesince }} ago.</p>
            {% if printer.status == "Printing" %}
                <p class="eta">Currently Printing.</p>
                <p class="eta">ETA: {{ printer.eta|timeuntil }}</p>
                <p class='eta'><progress value={{ printer.percent_done }} max=100></progress>
            {% endif %}
            {% if printer.status == "Print Done" %}
            <form action="{% url 'machines:clear_bed' printer.id %}" method="post">
                {% csrf_token %}
                <button class="card-button">Clear Bed.</button>
            </form>
            {% endif %}
            {% if printer.status == "Offline" %}
                <a href={{ printer.octoprint }}>Machine Offline, please check.</a>
            {% endif %}
        </div>
    {% endfor %}
</div>
{% endblock content %}

harp/machines/templates/machines/printer_form.html
{% extends 'machines/base.html' %}
{% load static %}

{% block content %}
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Add">
</form>
{% endblock %}

harp/machines/templates/machines/printers.html
{% extends 'machines/base.html' %}
{% load static %}

{% block content %}
<a href="{% url 'machines:machine_add' %}">Add Printer</a>

<table>
    <thead>
    <tr>
        <th>Name</th>
        <th>Status</th>
        <th>Last Update</th>
        <th>Tags</th>
        <th>Link</th>
        <th>Online</th>
        <th>Edit</th>
        <th>Delete</th>
    </tr>
    </thead>
    <tbody>
{% for printer in printers %}
        <tr>
            <td>{{ printer.name }}</td>
            <td>{{ printer.status }}</td>
            <td>{{ printer.last_updated|timesince }}</td>
            <td>
                {% for tag in printer.tags.all %}
                    <span class="tag-pill">{{ tag }}</span>
                {% endfor %}
            </td>
            <td><a href="{{ printer.octoprint }}">Visit</a></td>
            <td>
                <form action="{% url 'machines:machine_online_checkbox' printer.pk %}" method="post" target="_self">
                    {% csrf_token %}
                    <input type="checkbox" name="online" onChange="this.form.submit()" {% if printer.online %} checked {% endif %}>
                </form>
            </td>
            <td>Edit</td>
            <td><button class='delete_printer' data-pk={{ printer.pk }} data-name="{{ printer.name }}">Delete</button></td>
        </tr>
{% endfor %}
    </tbody>
</table>
{% endblock %}

{% block script %}
<script>
const deleteElement = document.querySelectorAll('.delete_printer');

deleteElement.forEach(function(item) {
    item.addEventListener('click', (event) => {
        const item_pk = event.target.getAttribute('data-pk');
        const item_name = event.target.getAttribute('data-name');

        let csrftoken = getCookie('csrftoken')

        if(confirm("Delete " + item_name + "?")) {
            let response = fetch('/machines/' + item_pk + '/delete', {
                method: "POST",
                headers: {
                    'Accept': 'application/json, text/plain, */*',
                    'Content-Type': 'application/json',
                    'X-CSRFToken': csrftoken 
                },
            });
            location.reload();
        }
    });
});
</script>
{% endblock %}

harp/machines/templates/machines/pushovercall_form.html
{% extends 'machines/base.html' %}
{% load static %}

{% block content %}
<form action='' method='post' enctype='multipart/form-data'>
    {% csrf_token %}
    {{ form.as_p }}
    <input type='submit' value='Add and Test'>
</form>
{% endblock content %}

harp/machines/templates/machines/queue.html
{% extends 'machines/base.html' %}
{% load static %}

{% block content %}
<h1>Current Queue</h1>
<table>
    <thead>
    <tr>
        <th class="queue-position">Position</th>
        <th>Name</th>
        <th class="queue-repeat">Quantity</th>
        <th class="queue-move">Move Position</th>
        <th class="queue-remove">Remove</th>
    </tr>
    </thead>
    <tbody>
    {% for item in queue %}
    <tr>
        <td>{% if item.currently_printing %} - {% else %}{{ item.position }}{% endif %}</td>
        <td>{{ item.cad_file.name }}</td>
        <td>
            <div>
                <input type="number" class='repeat' data-pk={{ item.pk }} id="repeat" min=1 size="1" value={{ item.amount_to_print }} name="repeat">
            </div>
        </td>
        <td>
            <div>
                <form action="{% url 'machines:queue_up' item.pk %}" method="post">
                    {% csrf_token %}
                    <button>U</button>
                </form>
                <form action="{% url 'machines:queue_down' item.pk %}" method="post">
                    {% csrf_token %}
                    <button>D</button>
                </form>
            </div>
        </td>
        <td>
            <form action="{% url 'machines:queue_delete' item.pk %}" method="post">
                {% csrf_token %}
                <button>Remove</button>
            </form>
        </td>
    </tr>
    </tbody>
    {% empty %}
    The current queue is empty, <a href="{% url 'machines:cad' %}">Add some here.</a>
    {% endfor %}
</table>
<script>
    const repeatElement = document.querySelectorAll('.repeat')

    repeatElement.forEach(function(item) {
        item.addEventListener('change', (event) => {
            const item_pk = event.target.getAttribute('data-pk');
            console.log(event.target.value);
            data = JSON.stringify({count: event.target.value});
            let csrftoken = getCookie('csrftoken');
            let response = fetch('/queue/' + item_pk + '/repeat', {
                method: "POST",
                body: data,
                headers: { 'Accept': 'application/json, text/plain, */*',
                            'Content-Type': 'application/json',
                            "X-CSRFToken": csrftoken },
            });
            console.log(item_pk);
        });
    });

function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = cookies[i].trim();
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }

    return cookieValue;
}
</script>
{% endblock %}